export { default as History } from './History'
export { default as ApplicationInformation } from './tab/ApplicationInformation'
export { default as Qualification } from './tab/Qualification'
export { default as EnterpriseRiskInformation } from './tab/EnterpriseRiskInformation'
export { default as PersonalQualification } from './tab/PersonalQualification'
export { default as PersonalRiskInformation } from './tab/PersonalRiskInformation'
export { default as AttachmentPreview } from './tab/AttachmentPreview'
